export const ADMIN_BOOK_LIST_REQUEST = 'ADMIN_BOOK_LIST_REQUEST';
export const ADMIN_BOOK_LIST_SUCCESS = 'ADMIN_BOOK_LIST_SUCCESS';
export const ADMIN_BOOK_LIST_FAIL = 'ADMIN_BOOK_LIST_FAIL';

export const ADMIN_BOOK_APPROVE_REQUEST = 'ADMIN_BOOK_APPROVE_REQUEST';
export const ADMIN_BOOK_APPROVE_SUCCESS = 'ADMIN_BOOK_APPROVE_SUCCESS';
export const ADMIN_BOOK_APPROVE_FAIL = 'ADMIN_BOOK_APPROVE_FAIL';


