export const BOOK_REQUEST_CREATE_REQUEST = "BOOK_REQUEST_CREATE_REQUEST";
export const BOOK_REQUEST_CREATE_SUCCESS = "BOOK_REQUEST_CREATE_SUCCESS";
export const BOOK_REQUEST_CREATE_FAIL = "BOOK_REQUEST_CREATE_FAIL";
export const BOOK_REQUEST_CREATE_RESET = "BOOK_REQUEST_CREATE_RESET";
