export const ISSUE_BOOK_REQUEST = "ISSUE_BOOK_REQUEST";
export const ISSUE_BOOK_SUCCESS = "ISSUE_BOOK_SUCCESS";
export const ISSUE_BOOK_FAIL = "ISSUE_BOOK_FAIL";
export const GET_ISSUED_BOOKS_REQUEST = "GET_ISSUED_BOOKS_REQUEST";
export const GET_ISSUED_BOOKS_SUCCESS = "GET_ISSUED_BOOKS_SUCCESS";
export const GET_ISSUED_BOOKS_FAILURE = "GET_ISSUED_BOOKS_FAILURE";