export const MESSAGE_CREATE_REQUEST = 'MESSAGE_CREATE_REQUEST';
export const MESSAGE_CREATE_SUCCESS = 'MESSAGE_CREATE_SUCCESS';
export const MESSAGE_CREATE_FAIL = 'MESSAGE_CREATE_FAIL';
export const MESSAGE_CREATE_RESET = 'MESSAGE_CREATE_RESET';
