export const RESERVATION_CREATE_REQUEST = "RESERVATION_CREATE_REQUEST";
export const RESERVATION_CREATE_SUCCESS = "RESERVATION_CREATE_SUCCESS";
export const RESERVATION_CREATE_FAIL = "RESERVATION_CREATE_FAIL";

export const RESERVATION_DETAILS_REQUEST = "RESERVATION_DETAILS_REQUEST";
export const RESERVATION_DETAILS_SUCCESS = "RESERVATION_DETAILS_SUCCESS";
export const RESERVATION_DETAILS_FAIL = "RESERVATION_DETAILS_FAIL";

export const MY_RESERVATION_LIST_REQUEST = "MY_RESERVATION_LIST_REQUEST";
export const MY_RESERVATION_LIST_SUCCESS = "MY_RESERVATION_LIST_SUCCESS";
export const MY_RESERVATION_LIST_FAIL = "MY_RESERVATION_LIST_FAIL";

export const RESERVATION_LIST_REQUEST = "RESERVATION_LIST_REQUEST";
export const RESERVATION_LIST_SUCCESS = "RESERVATION_LIST_SUCCESS";
export const RESERVATION_LIST_FAIL = "RESERVATION_LIST_FAIL";

export const RESERVATION_APPROVE_SUCCESS = "RESERVATION_APPROVE_SUCCESS";
export const RESERVATION_APPROVE_FAIL = "RESERVATION_APPROVE_FAIL";
export const RESERVATION_APPROVE_REQUEST = "RESERVATION_APPROVE_REQUEST";

export const RESERVATION_CANCEL_REQUEST = "RESERVATION_CANCEL_REQUEST";
export const RESERVATION_CANCEL_SUCCESS = "RESERVATION_CANCEL_SUCCESS";
export const RESERVATION_CANCEL_FAIL = "RESERVATION_CANCEL_FAIL";
